name: generate sbom

permissions:
  # set default workflow permissions to read-only for security reasons
  contents: read
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ master ]

jobs:

  gen-sbom:

    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@v3

    - id: gensbom
      uses: advanced-security/generate-sbom-action@v1

    - id: upload
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}
