name: generate sbom

permissions:
  # set default workflow permissions to read-only for security reasons
  contents: read
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ master ]

jobs:

  gen-sbom:

    runs-on: ubuntu-latest

    steps:
    - id: checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - id: gensbom
      uses: advanced-security/generate-sbom-action@ded26bf491ccc4b8c43f6c7ac2e1ff35e960c0d0 # v1

    - id: upload
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: sbom
        path: ${{ steps.gensbom.outputs.fileName }}
